name: kar-dask
channels:
  - conda-forge
dependencies:
  - python=3.9.4
  - pip=21.1.1
  - pylint=2.7.2
  - black=21.5b0
  - ipython=7.23.1
  - jupyter=1.0.0
  - jupyterlab=3.0.15
  - ipywidgets=7.6.3
  - pandas=1.2.4
  - numpy=1.20.2
  - pyarrow=4.0.0
  - h5py=2.10.0
  - scikit-image=0.16.2
  - scikit-learn=0.24.1
  - python-graphviz=0.16
  - dask=2021.4.1
  - dask-ml=1.9.0
  - dask-sql=0.3.6
  - dask-labextension=5.0.1
  - distributed=2021.4.1
